project_id: "365959"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: './crowdin'

preserve_hierarchy: true

files:
  - source: '**/docs.resx'
    translation: '**/%two_letters_code%/%original_file_name%'
