project_id: "365959"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: './crowdin'

preserve_hierarchy: true

files:
  - source: '**/docs.en.resx'
    dest: '**/docs.resx'
    translation: '**/docs.%two_letters_code%.resx'
