name: Upload to Crowdin

on:
  push:
    branches:
      - "*"

jobs:
  crowdin:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build resx files
        run: npm run build:resx

      - name: Run Crowdin upload
        run: |
          if [ "${{ github.ref_name }}" = "master" ]; then
            npm run crowdin:upload
          else
            npm run crowdin:upload:dryrun
          fi
